services:
  mysql:
    image: mysql:9.4
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    networks:
      - tribalingual-net
  be:
    image: tribalingual-be:latest
    container_name: tribalingual-be
    environment:
      - ENV_FILE=application.yaml
    ports:
      - '8080:3000'
    volumes:
      - './config/application.dev.yaml:/app/dist/config/application.yaml:ro'
    networks:
      - tribalingual-net
networks:
  tribalingual-net:
