database:
  host: 127.0.0.1
  port: 3306
  username: test
  password: test
  dbname: test_db
cloudinary:
  folder: folder
  cloud_name: test
  api_key: test
  api_secret: test
auth0:
  issuer: issuer-uri
  audience: http://localhost:3000/api
  secret: client-secret
