database:
  host: mysql
  port: 3306
  username: test
  password: test
  dbname: test_db
cloudinary:
  folder:
  cloud_name:
  api_key:
  api_secret:
auth0:
  issuer: https://<domain>/
  audience: http://localhost:3000/api
  jwks: https://<domain>/.well-known/jwks.json
  domain:
  client_id:
  client_secret:
  management_api_audience: https://<domain>/api/v2/
